if row['Item'] != 'EAVI Travel':
    pick_list = pick_list['Item']
elif row['Item'] != 'EAVI System Design Services':
    pick_list = pick_list['Item']
elif row['Item'] != 'EAVI Project Planning':
    pick_list = pick_list['Item']
elif row['Item'] != 'EAVI Hardware':
    pick_list = pick_list['Item']
elif row['Item'] != 'EAVI Installation Testing':
    pick_list = pick_list['Item']
elif row['Item'] != 'EAVI Training':
    pick_list = pick_list['Item']
elif row['Item'] != 'EAVI First Use':
    pick_list = pick_list['Item']
elif row['Item'] != 'EAVI System Commissioning':
    pick_list = pick_list['Item']
elif row['Item'] != "EAVI Rigging Location 8' to 12'":
    pick_list = pick_list['Item']
elif row['Item'] != "EAVI Rigging Loc.-12' to 30'":
    pick_list = pick_list['Item']
elif row['Item'] != 'EAVI LIFT RENTAL':
    pick_list = pick_list['Item']
elif row['Item'] != 'EAVI Allowance':
    pick_list = pick_list['Item']
elif row['Item'] != 'EAVI Custom Paint-Speakers':
    pick_list = pick_list['Item']
elif row['Item'] != 'EAVI Custom Power Contactor Box':
    pick_list = pick_list['Item']
elif row['Item'] != 'EAVI Custom Power Raceway':
    pick_list = pick_list['Item']
elif row['Item'] != 'EAVI OFE':
    pick_list = pick_list['Item']
